// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsbvldckqkxxicxjnlgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zYnZsZGNrcWt4eGljeGpubGdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjA1MjksImV4cCI6MjA1OTkzNjUyOX0.S8HtQvgdTYBJrLA456DGnzNJDqXbyUuzvARuHsVgB-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);